image: node:carbon

clone:
  depth: full

pipelines:
  default:
  - step:
      caches:
      - node
      - sonarcloud
      - node-scanner
      script:
      - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
      - npm install
      - npm run bootstrap-deps
      - npm install -g gulp
      - npm run build
      - npm run test:ci
      - npm run test:lint
      - npm run test:sonar
      services:
      - mongo
  - step:
      name: Deploy beta version
      trigger: manual
      deployment: staging
      caches:
      - node
      script:
      - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
      - npm install
      - npm run bootstrap-deps
      - npm install -g gulp
      - npm run build
      - npm run lerna-publish -- "--canary" "--preid beta"
  branches:
    master:
    - step:
        deployment: production
        caches:
        - node
        - sonarcloud
        - node-scanner
        script:
        - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
        - npm install
        - npm run bootstrap-deps
        - npm install -g gulp
        - npm run build
        - npm run test:ci
        - npm run test:lint
        - npm run test:sonar
        - npm run lerna-publish -- --no-git-tag-version --no-push
        services:
        - mongo

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner
  services:
    mongo:
      image: mongo