image: node:carbon

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
          - sonarcloud
          - node-scanner
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build -- --since master
          - npm run test:ci -- --since master
          - npm run test:lint -- --since master
          - npm run test:sonar -- --since master
        services: 
          - mongo
    - step:
        name: Deploy beta version
        trigger: manual
        caches:
          - node
        script:
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm run build -- --since develop
#          - npm publish --tag beta
  branches:
    master:
      - step:
          caches:
            - node
            - sonarcloud
            - node-scanner
          script:
            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
            - npm install
            - npm run build -- --since master
            - npm run test:ci -- --since master
            - npm run test:lint -- --since master
            - npm run test:sonar -- --since master
#            - npm publish
          services: 
            - mongo 

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner
  services: 
    mongo: 
      image: mongo