export enum Errors {
    AWS_RECEIVING_MESSAGES_FAILED = 'AWS_RECEIVING_MESSAGES_FAILED',
    AWS_SEND_MESSAGE_FAILED = 'AWS_SEND_MESSAGE_FAILED',
    AWS_SQS_SETTINGS_WAS_NOT_SPECIFIED = 'AWS_SQS_SETTINGS_WAS_NOT_SPECIFIED',
    AWS_SQS_CREATE_QUEUE_FAILED = 'AWS_SQS_CREATE_QUEUE_FAILED',
    AWS_SQS_GET_QUEUE_URL_FAILED = 'AWS_SQS_GET_QUEUE_URL_FAILED',
    AWS_SQS_LIST_QUEUE_FAILED = 'AWS_SQS_LIST_QUEUE_FAILED',
    AWS_SQS_DELETE_QUEUE_FAILED = 'AWS_SQS_DELETE_QUEUE_FAILED',

    GC_PUBSUB_CREATE_TOPIC_FAILED = 'GC_PUBSUB_CREATE_TOPIC_FAILED',
    GC_PUBSUB_LIST_TOPIC_FAILED = 'GC_PUBSUB_LIST_TOPIC_FAILED',
    GC_PUBSUB_DELETE_TOPIC_FAILED = 'GC_PUBSUB_DELETE_TOPIC_FAILED',
    GC_PUBSUB_SEND_MESSAGE_FAILED = 'GC_PUBSUB_SEND_MESSAGE_FAILED',
    GC_PUBSUB_RECEIVING_MESSAGE_FAILED = 'GC_PUBSUB_RECEIVING_MESSAGE_FAILED',
    GC_PUBSUB_PUBLISHER_SETTINGS_WAS_NOT_SPECIFIED = 'GC_PUBSUB_PUBLISHER_SETTINGS_WAS_NOT_SPECIFIED',
    GC_PUBSUB_SUBSCRIBER_SETTINGS_WAS_NOT_SPECIFIED = 'GC_PUBSUB_SUBSCRIBER_SETTINGS_WAS_NOT_SPECIFIED',
    GC_PUBSUB_METHOD_NOT_SUPPORTED = 'GC_PUBSUB_METHOD_NOT_SUPPORTED',
    GC_PUBSUB_CREATE_SUBSCRIPTION_FAILED = 'GC_PUBSUB_CREATE_SUBSCRIPTION_FAILED',

    KAFKA_CONFIG_NOT_FOUND = 'KAFKA_CONFIG_NOT_FOUND'
}
